# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0002_auto_20181107_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortinfo', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
