# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0004_shortinfo_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortinfo',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='shortinfo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='shortinfo',
        ),
    ]
