# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0009_doctor_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='pincode',
            new_name='pin',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='doctor',
        ),
        migrations.AddField(
            model_name='pincode',
            name='doctor',
            field=models.ManyToManyField(blank=True, to='webdoctor.doctor'),
        ),
    ]
