# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-10 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0011_auto_20181211_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='pin',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pun', to='webdoctor.Pin'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='Pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pn', to='webdoctor.Pin'),
        ),
    ]
