# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-11 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0012_auto_20181211_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='Pin',
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdoctor.PinCode'),
        ),
        migrations.AddField(
            model_name='pincode',
            name='pin',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdoctor.City'),
        ),
        migrations.DeleteModel(
            name='Pin',
        ),
    ]
