# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-12 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0014_doctor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(default=18, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('payment', models.BooleanField(default=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('doctorInConcern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdoctor.doctor')),
            ],
        ),
    ]
