# Generated by Django 2.1.2 on 2018-12-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0015_dochistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='docs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdoctor.doctor'),
        ),
    ]
