# Generated by Django 2.1.2 on 2018-12-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0016_pincode_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pincode',
            name='docs',
        ),
        migrations.AddField(
            model_name='pincode',
            name='docs',
            field=models.ManyToManyField(blank=True, null=True, to='webdoctor.doctor'),
        ),
        migrations.AlterField(
            model_name='pincode',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdoctor.Pin'),
        ),
    ]
