# Generated by Django 2.1.2 on 2018-12-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0017_auto_20181214_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincode',
            name='pin',
        ),
        migrations.AddField(
            model_name='pincode',
            name='pin',
            field=models.ManyToManyField(blank=True, null=True, to='webdoctor.Pin'),
        ),
    ]
