# Generated by Django 2.1.2 on 2018-12-14 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0019_auto_20181214_0546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pincode',
            name='pin',
        ),
        migrations.AddField(
            model_name='pincode',
            name='pin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webdoctor.Pin'),
        ),
    ]
