# Generated by Django 2.1.2 on 2018-12-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0020_auto_20181214_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=100, null=True)),
                ('lan', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
