# Generated by Django 2.1.2 on 2018-12-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdoctor', '0021_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
